# load system wide xinit
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

xset r rate 200 40
xrandr --output Virtual-1 --mode 2560x1600

# HiDPI
xrdb -merge ~/.Xresources

#WM
exec i3
